export const PUBSUB_CLIENT = 'PUBSUB_CLIENT';
export const PUBSUB_CONFIG_OPTIONS = "PUBSUB_CONFIG_OPTIONS";
export const PUBSUB_LOGGER = 'PUBSUB_LOGGER';
export const PUBSUB_MERGED_OPTIONS = 'PUBSUB_MERGED_OPTIONS';